Travel
kuchichan/object-oriented-programming pull request #24
Opened 2020-07-05 22:33 UTC by WojtekMs

2020-07-08 17:50 UTC, kuchichan requested changes
Please change pr to homework/oop1

2020-07-09 15:48 UTC, WojtekMs commented
Base branch changed to homework/oop1 from master :)

2020-07-10 10:42 UTC, kuchichan reviewed
Cool!

2020-07-10 10:42 UTC, kuchichan commented on shm/src/Travel.cpp
> +    for (auto elem : map_->getAllIslands()) {
Maybe some std::algorithm? find_if + remove (just to excercise ;d )

2020-07-10 10:42 UTC, kuchichan commented on shm/src/Travel.cpp
> +        TimeServiceLocator::getTime()->operator++();
Hmm this is somewhat suspicious - did you ensure, that during travel days are also changed on different objects ( i mean we are calling next day method on other observers) - we want to travel in space, not in time :)

2020-07-13 18:30 UTC, kuchichan commented on shm/src/Travel.cpp
> +        TimeServiceLocator::getTime()->operator++();
I have checked that - its Ok.

2020-07-15 12:43 UTC, kuchichan approved these changes

2020-07-15 12:45 UTC, kuchichan commented on shm/.gitignore
> +notes.txt
There is a .gitignore one directory up (above shm) - plase append that line there.

2020-07-15 13:14 UTC, merged